# Generated by Django 3.2.6 on 2021-09-20 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_auction_lst_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_lst',
            name='category',
            field=models.CharField(choices=[('fish', 'Fishing goods'), ('nt', 'Notebooks'), ('dt', 'Desktop Computer'), ('all', 'All categories'), ('shoe', 'Shoes'), ('ant', 'Antiquities')], default={('fish', 'Fishing goods'), ('nt', 'Notebooks'), ('dt', 'Desktop Computer'), ('all', 'All categories'), ('shoe', 'Shoes'), ('ant', 'Antiquities')}, max_length=67),
        ),
    ]
