# Generated by Django 3.2.6 on 2021-09-21 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_auction_lst_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_lst',
            name='category',
            field=models.CharField(choices=[('fish', 'Fishing goods'), ('ant', 'Antiquities'), ('nt', 'Notebooks'), ('dt', 'Desktop Computer'), ('shoe', 'Shoes'), ('all', 'All categories')], default={('fish', 'Fishing goods'), ('ant', 'Antiquities'), ('nt', 'Notebooks'), ('dt', 'Desktop Computer'), ('shoe', 'Shoes'), ('all', 'All categories')}, max_length=67),
        ),
    ]
