# Generated by Django 3.2.6 on 2021-09-21 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_auction_lst_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_lst',
            name='category',
            field=models.CharField(choices=[('dt', 'Desktop Computer'), ('nt', 'Notebooks'), ('all', 'All categories'), ('ant', 'Antiquities'), ('fish', 'Fishing goods'), ('shoe', 'Shoes')], default={('dt', 'Desktop Computer'), ('nt', 'Notebooks'), ('all', 'All categories'), ('ant', 'Antiquities'), ('fish', 'Fishing goods'), ('shoe', 'Shoes')}, max_length=67),
        ),
    ]
