# Generated by Django 3.2.6 on 2021-09-21 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_auction_lst_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_lst',
            name='category',
            field=models.CharField(choices=[('shoe', 'Shoes'), ('dt', 'Desktop Computer'), ('fish', 'Fishing goods'), ('all', 'All categories'), ('nt', 'Notebooks'), ('ant', 'Antiquities')], max_length=67),
        ),
    ]
