# Generated by Django 3.2.6 on 2021-09-21 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_auction_lst_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_lst',
            name='category',
            field=models.CharField(choices=[('pn', 'Pinot Noir'), ('mt', 'Merlot'), ('mc', 'Malbec'), ('cs', 'Cabernet Sauvignon'), ('sy', 'Syrah')], max_length=67),
        ),
    ]
