# Generated by Django 3.2.6 on 2021-09-21 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_alter_auction_lst_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_lst',
            name='category',
            field=models.CharField(choices=[('sy', 'Syrah'), ('mc', 'Malbec'), ('cs', 'Cabernet Sauvignon'), ('mt', 'Merlot'), ('pn', 'Pinot Noir')], max_length=67),
        ),
    ]
