# Generated by Django 4.1.dev20211210161305 on 2021-12-11 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_alter_auction_lst_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_lst',
            name='category',
            field=models.CharField(choices=[('sy', 'Syrah'), ('pb', 'Pinot Blanc'), ('cs', 'Cabernet Sauvignon'), ('cd', 'Chardonnay'), ('cf', 'Cabernet Franc'), ('mc', 'Malbec'), ('sb', 'Sauvignon Blanc'), ('sh', 'Shiraz'), ('pn', 'Pinot Noir'), ('mt', 'Merlot')], max_length=67),
        ),
    ]
