# Generated by Django 3.2.6 on 2021-10-23 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_alter_auction_lst_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction_lst',
            old_name='price',
            new_name='starting_bid',
        ),
        migrations.RenameField(
            model_name='auction_lst',
            old_name='item',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='auction_lst',
            name='category',
            field=models.CharField(choices=[('sb', 'Sauvignon Blanc'), ('pb', 'Pinot Blanc'), ('sy', 'Syrah'), ('cd', 'Chardonnay'), ('cs', 'Cabernet Sauvignon'), ('cf', 'Cabernet Franc'), ('mc', 'Malbec'), ('pn', 'Pinot Noir'), ('mt', 'Merlot'), ('sh', 'Shiraz')], max_length=67),
        ),
    ]
