# Generated by Django 4.1.dev20211210161305 on 2021-12-12 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_alter_auction_lst_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_lst',
            name='category',
            field=models.CharField(choices=[('cd', 'Chardonnay'), ('pb', 'Pinot Blanc'), ('sy', 'Syrah'), ('cs', 'Cabernet Sauvignon'), ('mt', 'Merlot'), ('cf', 'Cabernet Franc'), ('sb', 'Sauvignon Blanc'), ('pn', 'Pinot Noir'), ('sh', 'Shiraz'), ('mc', 'Malbec')], max_length=67),
        ),
    ]
