# Generated by Django 3.2.6 on 2021-10-23 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_auto_20211023_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_lst',
            name='category',
            field=models.CharField(choices=[('mt', 'Merlot'), ('cd', 'Chardonnay'), ('pn', 'Pinot Noir'), ('sb', 'Sauvignon Blanc'), ('pb', 'Pinot Blanc'), ('mc', 'Malbec'), ('sy', 'Syrah'), ('cf', 'Cabernet Franc'), ('sh', 'Shiraz'), ('cs', 'Cabernet Sauvignon')], max_length=67),
        ),
    ]
