# Generated by Django 3.2.6 on 2021-10-23 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_alter_auction_lst_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction_lst',
            name='bids',
        ),
        migrations.RemoveField(
            model_name='auction_lst',
            name='closed',
        ),
        migrations.RemoveField(
            model_name='auction_lst',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='auction_lst',
            name='idUser',
        ),
        migrations.RemoveField(
            model_name='auction_lst',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='auction_lst',
            name='tophorizon',
        ),
        migrations.AlterField(
            model_name='auction_lst',
            name='category',
            field=models.CharField(choices=[('sy', 'Syrah'), ('cs', 'Cabernet Sauvignon'), ('pn', 'Pinot Noir'), ('mt', 'Merlot'), ('cd', 'Chardonnay'), ('cf', 'Cabernet Franc'), ('pb', 'Pinot Blanc'), ('mc', 'Malbec'), ('sh', 'Shiraz'), ('sb', 'Sauvignon Blanc')], max_length=67),
        ),
    ]
