# Generated by Django 3.2.6 on 2021-11-04 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_auto_20211023_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_lst',
            name='category',
            field=models.CharField(choices=[('sb', 'Sauvignon Blanc'), ('cs', 'Cabernet Sauvignon'), ('sh', 'Shiraz'), ('cd', 'Chardonnay'), ('sy', 'Syrah'), ('cf', 'Cabernet Franc'), ('mc', 'Malbec'), ('pn', 'Pinot Noir'), ('mt', 'Merlot'), ('pb', 'Pinot Blanc')], max_length=67),
        ),
    ]
