# Generated by Django 4.1.dev20211210161305 on 2021-12-12 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_auction_alter_watchlist_listing_delete_auction_lst'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='category',
            field=models.CharField(choices=[('sb', 'Sauvignon Blanc'), ('sy', 'Syrah'), ('cd', 'Chardonnay'), ('pn', 'Pinot Noir'), ('cs', 'Cabernet Sauvignon'), ('mt', 'Merlot'), ('mc', 'Malbec'), ('sh', 'Shiraz'), ('cf', 'Cabernet Franc'), ('pb', 'Pinot Blanc')], max_length=67),
        ),
    ]
