# Generated by Django 3.2.9 on 2021-11-16 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_alter_auction_lst_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_lst',
            name='category',
            field=models.CharField(choices=[('pb', 'Pinot Blanc'), ('sy', 'Syrah'), ('cs', 'Cabernet Sauvignon'), ('pn', 'Pinot Noir'), ('sh', 'Shiraz'), ('cd', 'Chardonnay'), ('mc', 'Malbec'), ('cf', 'Cabernet Franc'), ('mt', 'Merlot'), ('sb', 'Sauvignon Blanc')], max_length=67),
        ),
    ]
