# Generated by Django 4.1.dev20211210161305 on 2021-12-13 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_listing_alter_watchlist_listing_delete_auction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('cd', 'Chardonnay'), ('mt', 'Merlot'), ('pb', 'Pinot Blanc'), ('pn', 'Pinot Noir'), ('mc', 'Malbec'), ('cs', 'Cabernet Sauvignon'), ('sh', 'Shiraz'), ('sb', 'Sauvignon Blanc'), ('cf', 'Cabernet Franc'), ('sy', 'Syrah')], max_length=67),
        ),
    ]
