# Generated by Django 4.1.dev20211210161305 on 2021-12-26 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_alter_listing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('sh', 'Shiraz'), ('pb', 'Pinot Blanc'), ('cs', 'Cabernet Sauvignon'), ('cf', 'Cabernet Franc'), ('pn', 'Pinot Noir'), ('cd', 'Chardonnay'), ('mt', 'Merlot'), ('sy', 'Syrah'), ('sb', 'Sauvignon Blanc'), ('mc', 'Malbec')], max_length=67),
        ),
    ]
