# Generated by Django 4.1.dev20211210161305 on 2021-12-27 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_alter_listing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('pb', 'Pinot Blanc'), ('mt', 'Merlot'), ('sh', 'Shiraz'), ('cf', 'Cabernet Franc'), ('cs', 'Cabernet Sauvignon'), ('sb', 'Sauvignon Blanc'), ('cd', 'Chardonnay'), ('mc', 'Malbec'), ('sy', 'Syrah'), ('pn', 'Pinot Noir')], max_length=67),
        ),
    ]
