# Generated by Django 4.1.dev20211210161305 on 2021-12-28 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_alter_listing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('pb', 'Pinot Blanc'), ('cs', 'Cabernet Sauvignon'), ('sb', 'Sauvignon Blanc'), ('sh', 'Shiraz'), ('pn', 'Pinot Noir'), ('sy', 'Syrah'), ('mc', 'Malbec'), ('cf', 'Cabernet Franc'), ('cd', 'Chardonnay'), ('mt', 'Merlot')], max_length=67),
        ),
    ]
