# Generated by Django 4.1.dev20211210161305 on 2022-01-03 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0020_alter_listing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('pb', 'Pinot Blanc'), ('cs', 'Cabernet Sauvignon'), ('sy', 'Syrah'), ('cf', 'Cabernet Franc'), ('mc', 'Malbec'), ('pn', 'Pinot Noir'), ('cd', 'Chardonnay'), ('sh', 'Shiraz'), ('sb', 'Sauvignon Blanc'), ('mt', 'Merlot')], max_length=67),
        ),
    ]
