# Generated by Django 4.1.dev20211210161305 on 2022-01-04 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0021_alter_listing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('cd', 'Chardonnay'), ('mt', 'Merlot'), ('pn', 'Pinot Noir'), ('sy', 'Syrah'), ('pb', 'Pinot Blanc'), ('sb', 'Sauvignon Blanc'), ('cf', 'Cabernet Franc'), ('cs', 'Cabernet Sauvignon'), ('sh', 'Shiraz'), ('mc', 'Malbec')], max_length=67),
        ),
    ]
