# Generated by Django 4.1.dev20211210161305 on 2022-01-04 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0022_alter_listing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('sb', 'Sauvignon Blanc'), ('cs', 'Cabernet Sauvignon'), ('sy', 'Syrah'), ('cd', 'Chardonnay'), ('mt', 'Merlot'), ('cf', 'Cabernet Franc'), ('sh', 'Shiraz'), ('pb', 'Pinot Blanc'), ('pn', 'Pinot Noir'), ('mc', 'Malbec')], max_length=67),
        ),
    ]
