# Generated by Django 4.1.dev20211210161305 on 2022-01-08 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0023_alter_listing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('sb', 'Sauvignon Blanc'), ('cf', 'Cabernet Franc'), ('sh', 'Shiraz'), ('pb', 'Pinot Blanc'), ('sy', 'Syrah'), ('mc', 'Malbec'), ('mt', 'Merlot'), ('pn', 'Pinot Noir'), ('cs', 'Cabernet Sauvignon'), ('cd', 'Chardonnay')], max_length=67),
        ),
    ]
