# Generated by Django 4.1.dev20211210161305 on 2022-01-08 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0025_alter_listing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('pn', 'Pinot Noir'), ('sy', 'Syrah'), ('mc', 'Malbec'), ('cd', 'Chardonnay'), ('pb', 'Pinot Blanc'), ('cf', 'Cabernet Franc'), ('sb', 'Sauvignon Blanc'), ('cs', 'Cabernet Sauvignon'), ('sh', 'Shiraz'), ('mt', 'Merlot')], max_length=67),
        ),
    ]
