# Generated by Django 4.1.dev20211210161305 on 2022-01-09 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0026_alter_listing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('pn', 'Pinot Noir'), ('sb', 'Sauvignon Blanc'), ('sh', 'Shiraz'), ('mc', 'Malbec'), ('pb', 'Pinot Blanc'), ('mt', 'Merlot'), ('sy', 'Syrah'), ('cs', 'Cabernet Sauvignon'), ('cf', 'Cabernet Franc'), ('cd', 'Chardonnay')], max_length=67),
        ),
    ]
