# Generated by Django 4.1.dev20211210161305 on 2022-01-09 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0028_alter_listing_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='idUser',
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('sb', 'Sauvignon Blanc'), ('cs', 'Cabernet Sauvignon'), ('mc', 'Malbec'), ('cd', 'Chardonnay'), ('pb', 'Pinot Blanc'), ('sh', 'Shiraz'), ('cf', 'Cabernet Franc'), ('pn', 'Pinot Noir'), ('mt', 'Merlot'), ('sy', 'Syrah')], max_length=67),
        ),
    ]
