# Generated by Django 4.1.dev20211210161305 on 2022-01-10 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0029_remove_listing_iduser_alter_listing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('sh', 'Shiraz'), ('sb', 'Sauvignon Blanc'), ('cd', 'Chardonnay'), ('pb', 'Pinot Blanc'), ('cf', 'Cabernet Franc'), ('cs', 'Cabernet Sauvignon'), ('mc', 'Malbec'), ('pn', 'Pinot Noir'), ('mt', 'Merlot'), ('sy', 'Syrah')], max_length=67),
        ),
    ]
