# Generated by Django 4.1.dev20211210161305 on 2022-01-16 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0033_alter_listing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('sy', 'Syrah'), ('sb', 'Sauvignon Blanc'), ('mt', 'Merlot'), ('pn', 'Pinot Noir'), ('cf', 'Cabernet Franc'), ('cs', 'Cabernet Sauvignon'), ('pb', 'Pinot Blanc'), ('cd', 'Chardonnay'), ('sh', 'Shiraz'), ('mc', 'Malbec')], max_length=67),
        ),
    ]
