# Generated by Django 4.1.dev20211210161305 on 2022-01-16 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0034_alter_listing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('mt', 'Merlot'), ('sh', 'Shiraz'), ('cs', 'Cabernet Sauvignon'), ('cf', 'Cabernet Franc'), ('cd', 'Chardonnay'), ('sb', 'Sauvignon Blanc'), ('pn', 'Pinot Noir'), ('sy', 'Syrah'), ('mc', 'Malbec'), ('pb', 'Pinot Blanc')], max_length=67),
        ),
    ]
