# Generated by Django 4.1.dev20211210161305 on 2022-01-16 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0035_alter_listing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('pb', 'Pinot Blanc'), ('cd', 'Chardonnay'), ('mt', 'Merlot'), ('mc', 'Malbec'), ('cs', 'Cabernet Sauvignon'), ('pn', 'Pinot Noir'), ('cf', 'Cabernet Franc'), ('sy', 'Syrah'), ('sb', 'Sauvignon Blanc'), ('sh', 'Shiraz')], max_length=67),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='imgs/'),
        ),
    ]
