# Generated by Django 4.1.dev20211210161305 on 2022-01-16 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0036_alter_listing_category_alter_listing_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('pb', 'Pinot Blanc'), ('cf', 'Cabernet Franc'), ('sh', 'Shiraz'), ('pn', 'Pinot Noir'), ('mc', 'Malbec'), ('cd', 'Chardonnay'), ('sy', 'Syrah'), ('mt', 'Merlot'), ('sb', 'Sauvignon Blanc'), ('cs', 'Cabernet Sauvignon')], max_length=67),
        ),
    ]
