# Generated by Django 4.1.dev20211210161305 on 2022-01-16 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0037_alter_listing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('pb', 'Pinot Blanc'), ('pn', 'Pinot Noir'), ('sh', 'Shiraz'), ('cd', 'Chardonnay'), ('cs', 'Cabernet Sauvignon'), ('mc', 'Malbec'), ('sy', 'Syrah'), ('mt', 'Merlot'), ('cf', 'Cabernet Franc'), ('sb', 'Sauvignon Blanc')], max_length=67),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='auctions/static/media/'),
        ),
    ]
