# Generated by Django 4.1.dev20211210161305 on 2022-01-17 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0039_alter_listing_category_alter_listing_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('pb', 'Pinot Blanc'), ('cd', 'Chardonnay'), ('mc', 'Malbec'), ('cs', 'Cabernet Sauvignon'), ('sy', 'Syrah'), ('cf', 'Cabernet Franc'), ('sb', 'Sauvignon Blanc'), ('pn', 'Pinot Noir'), ('mt', 'Merlot'), ('sh', 'Shiraz')], max_length=67),
        ),
    ]
