# Generated by Django 4.1.dev20211210161305 on 2022-01-17 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0040_alter_listing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('sh', 'Shiraz'), ('cf', 'Cabernet Franc'), ('pn', 'Pinot Noir'), ('pb', 'Pinot Blanc'), ('mc', 'Malbec'), ('sy', 'Syrah'), ('mt', 'Merlot'), ('cs', 'Cabernet Sauvignon'), ('cd', 'Chardonnay'), ('sb', 'Sauvignon Blanc')], max_length=67),
        ),
    ]
