# Generated by Django 4.1.dev20211210161305 on 2022-01-17 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0041_alter_listing_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='bids',
            new_name='bid',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='bids',
        ),
        migrations.AddField(
            model_name='listing',
            name='bid',
            field=models.ManyToManyField(blank=True, related_name='bid', to='auctions.bid'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('pn', 'Pinot Noir'), ('sb', 'Sauvignon Blanc'), ('cs', 'Cabernet Sauvignon'), ('pb', 'Pinot Blanc'), ('sy', 'Syrah'), ('sh', 'Shiraz'), ('mc', 'Malbec'), ('cf', 'Cabernet Franc'), ('mt', 'Merlot'), ('cd', 'Chardonnay')], max_length=67),
        ),
    ]
