# Generated by Django 4.1.dev20211210161305 on 2022-01-18 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0042_rename_bids_bid_remove_listing_bids_listing_bid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('cs', 'Cabernet Sauvignon'), ('sh', 'Shiraz'), ('mc', 'Malbec'), ('mt', 'Merlot'), ('sy', 'Syrah'), ('cd', 'Chardonnay'), ('cf', 'Cabernet Franc'), ('sb', 'Sauvignon Blanc'), ('pb', 'Pinot Blanc'), ('pn', 'Pinot Noir')], max_length=67),
        ),
    ]
