# Generated by Django 4.1.dev20211210161305 on 2022-01-19 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0043_alter_listing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('sh', 'Shiraz'), ('cd', 'Chardonnay'), ('pb', 'Pinot Blanc'), ('sy', 'Syrah'), ('sb', 'Sauvignon Blanc'), ('pn', 'Pinot Noir'), ('mc', 'Malbec'), ('cs', 'Cabernet Sauvignon'), ('mt', 'Merlot'), ('cf', 'Cabernet Franc')], max_length=67),
        ),
    ]
