# Generated by Django 4.1.dev20211210161305 on 2022-01-19 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0044_alter_listing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('pn', 'Pinot Noir'), ('cd', 'Chardonnay'), ('pb', 'Pinot Blanc'), ('cs', 'Cabernet Sauvignon'), ('sh', 'Shiraz'), ('mt', 'Merlot'), ('mc', 'Malbec'), ('cf', 'Cabernet Franc'), ('sb', 'Sauvignon Blanc'), ('sy', 'Syrah')], max_length=67),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing', to='auctions.listing'),
        ),
    ]
