# Generated by Django 4.1.dev20211210161305 on 2022-01-19 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0045_alter_listing_category_alter_watchlist_listing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('mc', 'Malbec'), ('pn', 'Pinot Noir'), ('mt', 'Merlot'), ('sy', 'Syrah'), ('sh', 'Shiraz'), ('cs', 'Cabernet Sauvignon'), ('cf', 'Cabernet Franc'), ('sb', 'Sauvignon Blanc'), ('pb', 'Pinot Blanc'), ('cd', 'Chardonnay')], max_length=67),
        ),
    ]
