# Generated by Django 4.1.dev20211210161305 on 2022-01-19 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0046_alter_listing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('pb', 'Pinot Blanc'), ('mc', 'Malbec'), ('cf', 'Cabernet Franc'), ('sh', 'Shiraz'), ('cd', 'Chardonnay'), ('cs', 'Cabernet Sauvignon'), ('pn', 'Pinot Noir'), ('sy', 'Syrah'), ('sb', 'Sauvignon Blanc'), ('mt', 'Merlot')], max_length=67),
        ),
    ]
