# Generated by Django 4.1.dev20211210161305 on 2022-01-19 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0047_alter_listing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('cf', 'Cabernet Franc'), ('sh', 'Shiraz'), ('pb', 'Pinot Blanc'), ('pn', 'Pinot Noir'), ('sb', 'Sauvignon Blanc'), ('cs', 'Cabernet Sauvignon'), ('mc', 'Malbec'), ('mt', 'Merlot'), ('sy', 'Syrah'), ('cd', 'Chardonnay')], max_length=67),
        ),
    ]
