# Generated by Django 4.1.dev20211210161305 on 2022-01-19 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0048_alter_listing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('pn', 'Pinot Noir'), ('cs', 'Cabernet Sauvignon'), ('pb', 'Pinot Blanc'), ('cd', 'Chardonnay'), ('mt', 'Merlot'), ('sh', 'Shiraz'), ('sy', 'Syrah'), ('sb', 'Sauvignon Blanc'), ('mc', 'Malbec'), ('cf', 'Cabernet Franc')], max_length=67),
        ),
    ]
