# Generated by Django 4.1.dev20211210161305 on 2022-01-21 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0049_alter_listing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('mt', 'Merlot'), ('sb', 'Sauvignon Blanc'), ('pb', 'Pinot Blanc'), ('sy', 'Syrah'), ('sh', 'Shiraz'), ('cs', 'Cabernet Sauvignon'), ('pn', 'Pinot Noir'), ('mc', 'Malbec'), ('cd', 'Chardonnay'), ('cf', 'Cabernet Franc')], max_length=67),
        ),
    ]
