# Generated by Django 4.1.dev20211210161305 on 2022-01-26 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0050_alter_listing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('cf', 'Cabernet Franc'), ('sh', 'Shiraz'), ('cs', 'Cabernet Sauvignon'), ('pn', 'Pinot Noir'), ('sy', 'Syrah'), ('sb', 'Sauvignon Blanc'), ('mc', 'Malbec'), ('cd', 'Chardonnay'), ('mt', 'Merlot'), ('pb', 'Pinot Blanc')], max_length=67),
        ),
    ]
