# Generated by Django 4.1.dev20211210161305 on 2022-01-27 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0051_alter_listing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('mt', 'Merlot'), ('cd', 'Chardonnay'), ('sh', 'Shiraz'), ('sy', 'Syrah'), ('pb', 'Pinot Blanc'), ('cs', 'Cabernet Sauvignon'), ('cf', 'Cabernet Franc'), ('mc', 'Malbec'), ('sb', 'Sauvignon Blanc'), ('pn', 'Pinot Noir')], max_length=67),
        ),
    ]
