# Generated by Django 4.1.dev20211210161305 on 2022-01-28 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0053_remove_comment_iduser_alter_listing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('mt', 'Merlot'), ('sy', 'Syrah'), ('cd', 'Chardonnay'), ('cs', 'Cabernet Sauvignon'), ('sh', 'Shiraz'), ('cf', 'Cabernet Franc'), ('sb', 'Sauvignon Blanc'), ('pb', 'Pinot Blanc'), ('mc', 'Malbec'), ('pn', 'Pinot Noir')], max_length=67),
        ),
    ]
