# Generated by Django 4.1.dev20211210161305 on 2022-01-29 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0056_alter_listing_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='idUser',
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('mt', 'Merlot'), ('cs', 'Cabernet Sauvignon'), ('sy', 'Syrah'), ('sh', 'Shiraz'), ('sb', 'Sauvignon Blanc'), ('cd', 'Chardonnay'), ('mc', 'Malbec'), ('pb', 'Pinot Blanc'), ('pn', 'Pinot Noir'), ('cf', 'Cabernet Franc')], max_length=67),
        ),
    ]
