# Generated by Django 4.1.dev20211210161305 on 2022-01-29 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0057_remove_bid_iduser_alter_listing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('pb', 'Pinot Blanc'), ('sb', 'Sauvignon Blanc'), ('cs', 'Cabernet Sauvignon'), ('cf', 'Cabernet Franc'), ('sy', 'Syrah'), ('mt', 'Merlot'), ('sh', 'Shiraz'), ('cd', 'Chardonnay'), ('pn', 'Pinot Noir'), ('mc', 'Malbec')], max_length=67),
        ),
    ]
