# Generated by Django 4.1.dev20211210161305 on 2022-01-29 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0058_alter_listing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('sh', 'Shiraz'), ('sb', 'Sauvignon Blanc'), ('cd', 'Chardonnay'), ('sy', 'Syrah'), ('pb', 'Pinot Blanc'), ('mc', 'Malbec'), ('cf', 'Cabernet Franc'), ('mt', 'Merlot'), ('pn', 'Pinot Noir'), ('cs', 'Cabernet Sauvignon')], max_length=67),
        ),
    ]
