# Generated by Django 4.1.dev20211210161305 on 2022-01-29 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0059_alter_listing_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='wlTitle',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('cf', 'Cabernet Franc'), ('sb', 'Sauvignon Blanc'), ('pn', 'Pinot Noir'), ('sy', 'Syrah'), ('pb', 'Pinot Blanc'), ('cs', 'Cabernet Sauvignon'), ('mt', 'Merlot'), ('mc', 'Malbec'), ('cd', 'Chardonnay'), ('sh', 'Shiraz')], max_length=67),
        ),
    ]
