# Generated by Django 4.1.dev20211210161305 on 2022-01-29 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0066_alter_listing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('pn', 'Pinot Noir'), ('cs', 'Cabernet Sauvignon'), ('cf', 'Cabernet Franc'), ('sy', 'Syrah'), ('mt', 'Merlot'), ('sb', 'Sauvignon Blanc'), ('mc', 'Malbec'), ('cd', 'Chardonnay'), ('sh', 'Shiraz'), ('pb', 'Pinot Blanc')], max_length=67),
        ),
    ]
