# Generated by Django 4.1.dev20211210161305 on 2022-01-30 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0068_alter_listing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('sy', 'Syrah'), ('mt', 'Merlot'), ('mc', 'Malbec'), ('sb', 'Sauvignon Blanc'), ('sh', 'Shiraz'), ('cs', 'Cabernet Sauvignon'), ('pn', 'Pinot Noir'), ('pb', 'Pinot Blanc'), ('cf', 'Cabernet Franc'), ('cd', 'Chardonnay')], max_length=67),
        ),
    ]
