# Generated by Django 4.1.dev20211210161305 on 2022-01-30 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0069_alter_listing_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='title',
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('sb', 'Sauvignon Blanc'), ('pb', 'Pinot Blanc'), ('cf', 'Cabernet Franc'), ('pn', 'Pinot Noir'), ('cd', 'Chardonnay'), ('mt', 'Merlot'), ('sh', 'Shiraz'), ('mc', 'Malbec'), ('cs', 'Cabernet Sauvignon'), ('sy', 'Syrah')], max_length=67),
        ),
    ]
