# Generated by Django 4.1.dev20211210161305 on 2022-02-07 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0073_alter_listing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('pn', 'Pinot Noir'), ('mc', 'Malbec'), ('cd', 'Chardonnay'), ('pb', 'Pinot Blanc'), ('sb', 'Sauvignon Blanc'), ('cf', 'Cabernet Franc'), ('sy', 'Syrah'), ('mt', 'Merlot'), ('sh', 'Shiraz'), ('cs', 'Cabernet Sauvignon')], max_length=67),
        ),
    ]
