# Generated by Django 4.1.dev20211210161305 on 2022-02-07 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0075_alter_listing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('cs', 'Cabernet Sauvignon'), ('mc', 'Malbec'), ('cd', 'Chardonnay'), ('mt', 'Merlot'), ('cf', 'Cabernet Franc'), ('pn', 'Pinot Noir'), ('sy', 'Syrah'), ('pb', 'Pinot Blanc'), ('sh', 'Shiraz'), ('sb', 'Sauvignon Blanc')], max_length=67),
        ),
    ]
