# Generated by Django 4.1.dev20211210161305 on 2022-02-07 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0076_alter_listing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('sb', 'Sauvignon Blanc'), ('cd', 'Chardonnay'), ('sh', 'Shiraz'), ('sy', 'Syrah'), ('pn', 'Pinot Noir'), ('mt', 'Merlot'), ('pb', 'Pinot Blanc'), ('cs', 'Cabernet Sauvignon'), ('mc', 'Malbec'), ('cf', 'Cabernet Franc')], max_length=67),
        ),
    ]
