# Generated by Django 4.1.dev20211210161305 on 2022-02-07 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0077_alter_listing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('pb', 'Pinot Blanc'), ('sy', 'Syrah'), ('pn', 'Pinot Noir'), ('sb', 'Sauvignon Blanc'), ('mt', 'Merlot'), ('mc', 'Malbec'), ('cs', 'Cabernet Sauvignon'), ('sh', 'Shiraz'), ('cd', 'Chardonnay'), ('cf', 'Cabernet Franc')], max_length=67),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo',
            field=models.URLField(blank=True),
        ),
    ]
