# Generated by Django 4.1.dev20211210161305 on 2022-02-07 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0078_alter_listing_category_alter_listing_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('cf', 'Cabernet Franc'), ('sb', 'Sauvignon Blanc'), ('sy', 'Syrah'), ('cd', 'Chardonnay'), ('pn', 'Pinot Noir'), ('mc', 'Malbec'), ('cs', 'Cabernet Sauvignon'), ('mt', 'Merlot'), ('sh', 'Shiraz'), ('pb', 'Pinot Blanc')], max_length=67),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
