# Generated by Django 4.1.dev20211210161305 on 2022-02-09 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0081_alter_listing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('sh', 'Shiraz'), ('sb', 'Sauvignon Blanc'), ('cs', 'Cabernet Sauvignon'), ('mc', 'Malbec'), ('sy', 'Syrah'), ('pn', 'Pinot Noir'), ('mt', 'Merlot'), ('pb', 'Pinot Blanc'), ('cf', 'Cabernet Franc'), ('cd', 'Chardonnay')], max_length=67),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
