# Generated by Django 4.1.dev20211210161305 on 2022-02-09 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0083_alter_listing_category_alter_listing_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('pb', 'Pinot Blanc'), ('cf', 'Cabernet Franc'), ('sh', 'Shiraz'), ('pn', 'Pinot Noir'), ('sy', 'Syrah'), ('cd', 'Chardonnay'), ('mt', 'Merlot'), ('mc', 'Malbec'), ('cs', 'Cabernet Sauvignon'), ('sb', 'Sauvignon Blanc')], max_length=67),
        ),
    ]
